### ISSUE TITLE
A little advice about Chinese translation

### ISSUE THREAD

**Issue by JoeHetfield** [learning/underscore#2]
Hi, I read the Underscore.js Chinese translated document.
I’m really glad to see there are someone doing this! 
Thanks, and this will help a lots of people that more than you can imaging!
I just focused on the Utility--template part, and I felt there are little bit of miss and some improvement could be made. This is my version of translation:

template_.template(templateString, [data], [settings]) 
将Javascript模板编译为可以用于描绘页面的函数。在从JSON数据源中描绘出一些复杂的HTML时十分有用。模板函数中既可以使用“<%= … %>”插入变量，也可以使用“<% … %>”来执行任意的Javascript代码。如果你想插入一个经过HTML转义处理的值，可以使用“<%- … %>”。当你使用模板函数时，传入一个data对象，这个data对象应当拥有对应于模板中的各个自由变量的属性成员。如果你只是想写一个一次性的代码段，你可以将data对象作为template的第二个参数传入以便立即进行描绘，而非返回一个模板函数。setting参数应当是一个哈希表，包含任何应当被覆盖的_.templateSetting的值。

// code goes here

你也可以在模板的Javascript中使用print。这有时比使用“<%= … %>”更方便。

// code goes here

如果你不喜欢ERB式的分隔符，你可以更改以下Underscore的模板设定来使用不同的符号来标识插入的代码：一个名为interpolate正则表达式来匹配那些应当被作为插入部分的字符，一个名为escape正则表达式来匹配那些应当经过HTML转义处理后被插入的表达式，以及一个名为evaluate正则表达式来匹配那些应当被执行但不插入最终的结果字符串的表达式。你可以定义或忽略这三个正则表达式的任意组合。比如，如果要实施Mustache.js式的模板的话：

// code goes here

默认情况下，template通过with语句在本地作用域的数据中定位值。不过，你可以用variable设定来设定一个单独的变量名。这可以显著提高一个可以被描绘的模板的速度。

// code goes here

在对一个你不能再现的错误进行调试时，预编译你的模板非常有帮助。因为预编译模板可以提供行号和调用栈轨迹，这是在客户端进行编译时不可能得到的。在已经编译的模函数上，有一个source属性用来简单地进行预编译。

// code goes here

That's it. I think this one is much easier to understand for native Chinese reader.
I'll check the rest of the document, and post any thing I noticed. If there are any thing mistake in this translation, please tell me by mail. 
(if you need futher help or my version is adopted, please mail me too!)

**Comment by runningair** [comment]
非常好的翻译! Thx to JoeHetfield!

**Comment by learning** [comment]
最近在更新1.5.2版本的，将会考虑加上，谢谢JoeHetfield

**Comment by JoeHetfield** [comment]
谢谢二位的认可，如果有什么能够帮忙的，请不要客气，尽管告诉我
