### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by xuemengfei** [learning/underscore#4]
template
 "模板函数可以通过以下两种方式插入到页面中, 使用 <%= … %>, 也可以用<% … %>执行任意的 JavaScript 代码."
原文是
“ Template functions can both interpolate variables, using <%= … %>, as well as execute arbitrary JavaScript code, with <% … %>.”
翻译应该是
“用<%= … %>插入变量，用<% … %>执行任意的JS代码“

" 如果您希望插入一个值, 并让其进行HTML转义, 当您使用创建一个模板时使用 <%- … %> , 传入一个含有与模板对应属性的对象 data"
原文
“ If you wish to interpolate a value, and have it be HTML-escaped, use <%- … %> When you evaluate a template function, pass in a data object that has properties corresponding to the template's free variables.”
原文应该是在When前面少写了一个句号……所以这里翻译出来会有问题

chain
"知道 value 方法"

**Comment by learning** [comment]
最近在更新1.5.2版本的，会作修改，谢谢。
